import { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/router';
import RadarChart from '../components/RadarChart';

const IDEA_POOL = [
  'AI SaaS tool', 'D2C skincare brand', 'B2B data API', 'Micro-SaaS for creators',
  'Newsletter business', 'Productized design service', 'AI hiring tool', 'No-code app builder',
  'Marketplace for freelancers', 'EdTech for India', 'FinTech for SMBs', 'Health tracking app',
  'AI legal assistant', 'Creator monetization tool', 'B2B cold outreach tool', 'E-commerce aggregator'
];

const AGENTS = [
  { name: 'Demand analysis',      status: 'scanning search trends' },
  { name: 'Margin model',         status: 'estimating unit economics' },
  { name: 'Market gap scan',      status: 'finding whitespace' },
  { name: 'Competitor landscape', status: 'mapping players' },
  { name: 'Buyer personas',       status: 'profiling segments' },
  { name: 'Acquisition channels', status: 'scoring CAC' },
  { name: 'Legal requirements',   status: 'checking compliance' },
  { name: 'Exit potential',       status: 'valuing multiples' },
  { name: 'Opportunity score',    status: 'finalising verdict' },
];

const KIRA_LINES = [
  'Give me a moment. Looking at the market...',
  'Interesting space. Pulling competitor data...',
  'Running the numbers...',
  'Almost there. Scoring the opportunity...',
  "Here's what I found.",
];

const TABS = ['Overview', 'Score', 'Market', 'Personas', 'Channels', 'Legal', 'Blueprint'];

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ─── Shared report-to-markdown builder ───────────────────────────────────────
function buildMarkdown(report, idea) {
  const lines = [];
  lines.push(`# Kira Analysis: ${idea}`);
  lines.push('');
  lines.push(`**Verdict:** ${report.decision}`);
  lines.push('');
  lines.push(report.decisionReason);
  if (report.pivotAngle) {
    lines.push('');
    lines.push(`**If you pivoted:** ${report.pivotAngle}`);
  }
  lines.push('');
  lines.push('## Metrics');
  report.metrics?.forEach(m => { lines.push(`- **${m.l}:** ${m.v}`); if (m.s) lines.push(`  *${m.s}*`); });
  lines.push('');
  lines.push('## Market Gaps');
  report.gaps?.forEach(g => lines.push(`→ ${g}`));
  lines.push('');
  lines.push('## Risks');
  report.risks?.forEach(r => {
    if (typeof r === 'string') lines.push(`- ${r}`);
    else { lines.push(`- **${r.r}**`); if (r.m) lines.push(`  Mitigation: ${r.m}`); }
  });
  lines.push('');
  lines.push('## Revenue Forecast');
  report.forecastBars?.forEach(f => lines.push(`- **${f.label}:** ${f.val}`));
  lines.push('');
  lines.push('## Score');
  if (report.scores) {
    const vals = Object.values(report.scores);
    lines.push(`**Overall: ${Math.round(vals.reduce((a, b) => a + b, 0) / vals.length)} / 100**`);
    lines.push('');
    const labels = { marketSize: 'Market Size', differentiation: 'Differentiation', marginQuality: 'Margin Quality', capitalEfficiency: 'Capital Efficiency', executionComplexity: 'Execution Complexity', scalability: 'Scalability' };
    Object.entries(report.scores).forEach(([k, v]) => lines.push(`- **${labels[k] || k}:** ${v}/100`));
  }
  lines.push('');
  lines.push('## Competitor Landscape');
  report.competitors?.forEach(c => {
    lines.push(`### ${c.name} — ${c.share}% market share`);
    lines.push(`- Weakness: ${c.weakness}`);
    lines.push(`- Threat: ${c.threat}`);
  });
  lines.push('');
  lines.push('## Buyer Personas');
  report.personas?.forEach(p => {
    lines.push(`### ${p.name} — ${p.tag}`);
    lines.push(`- Age: ${p.age}`);
    lines.push(`- Channels: ${Array.isArray(p.channels) ? p.channels.join(', ') : p.channels}`);
    lines.push(`- Pain: ${p.pain}`);
    lines.push(`- Trigger: ${p.trigger}`);
  });
  lines.push('');
  lines.push('## Acquisition Channels');
  report.channels?.forEach(c => {
    lines.push(`### ${c.name} — ${c.fit}`);
    lines.push(`- CAC: ${c.cac}`);
    if (c.note) lines.push(`- ${c.note}`);
  });
  lines.push('');
  lines.push('## Legal Requirements');
  report.legal?.forEach(l => lines.push(`✓ ${l}`));
  lines.push('');
  lines.push('## Exit Potential');
  if (report.exit) {
    lines.push(`- Yr 3 Revenue: ${report.exit.yr3Rev}`);
    lines.push(`- Multiple: ${report.exit.multiple}`);
    lines.push(`- Valuation: ${report.exit.yr3Val}`);
    lines.push(`- Buyers: ${report.exit.buyers}`);
  }
  lines.push('');
  lines.push('## Product Spec');
  report.spec?.forEach(([label, value]) => lines.push(`- **${label}:** ${value}`));
  lines.push('');
  lines.push('## Launch Roadmap');
  report.roadmap?.forEach(([time, action]) => lines.push(`- **${time}:** ${action}`));
  lines.push('');
  lines.push('---');
  lines.push('*Generated by Kira — business-intelligence-engine.vercel.app*');
  return lines.join('\n');
}

export default function Home() {
  const router = useRouter();

  // phases: input | running | results | error
  const [phase, setPhase] = useState('input');
  const [idea, setIdea] = useState('');
  const [chips, setChips] = useState(IDEA_POOL.slice(0, 4));
  const [spinning, setSpinning] = useState(false);
  const [versionOpen, setVersionOpen] = useState(false);
  const [version, setVersion] = useState('Kira 1.0');

  const [agentStates, setAgentStates] = useState(AGENTS.map(() => 'pending')); // pending | running | done
  const [kiraLine, setKiraLine] = useState('');

  const [report, setReport] = useState(null);
  const [activeTab, setActiveTab] = useState('Overview');
  const [error, setError] = useState('');

  const textareaRef = useRef(null);

  // Restore from URL share
  useEffect(() => {
    const { idea: qi, data: qd } = router.query;
    if (qi && qd) {
      try {
        const restored = JSON.parse(decodeURIComponent(atob(qd)));
        setIdea(decodeURIComponent(qi));
        setReport(restored);
        setPhase('results');
      } catch {}
    }
  }, [router.query]);

  // Shuffle chips
  const shuffle = () => {
    setSpinning(true);
    setTimeout(() => setSpinning(false), 400);
    const pool = [...IDEA_POOL].sort(() => Math.random() - 0.5).slice(0, 4);
    setChips(pool);
  };

  // Submit
  const submit = async () => {
    if (!idea.trim()) return;
    setPhase('running');
    setAgentStates(AGENTS.map(() => 'pending'));
    setKiraLine('');
    setError('');

    const animPromise = runAnimation();
    const apiPromise = fetch('/api/analyze', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ idea }),
    }).then((r) => r.json());

    const [, data] = await Promise.all([animPromise, apiPromise]);

    if (data.error) {
      setError(data.error);
      setPhase('error');
    } else {
      setReport(data);
      setActiveTab('Overview');
      setPhase('results');
    }
  };

  const runAnimation = async () => {
    await sleep(600);
    setKiraLine(KIRA_LINES[0]);

    for (let i = 0; i < AGENTS.length; i++) {
      await sleep(i === 0 ? 400 : 320);
      setAgentStates((prev) => { const n = [...prev]; n[i] = 'running'; return n; });

      if (i === 2) { await sleep(80); setKiraLine(KIRA_LINES[1]); }
      if (i === 5) { await sleep(80); setKiraLine(KIRA_LINES[2]); }
      if (i === 7) { await sleep(80); setKiraLine(KIRA_LINES[3]); }

      await sleep(i < 3 ? 900 : i < 6 ? 1100 : 1300);
      setAgentStates((prev) => { const n = [...prev]; n[i] = 'done'; return n; });
    }

    await sleep(500);
    setKiraLine(KIRA_LINES[4]);
    await sleep(800);
  };

  const handleKey = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submit(); }
  };

  // ─── FIXED: Full report copy ──────────────────────────────────────────────
  const copyReport = () => {
    if (!report) return;
    navigator.clipboard.writeText(buildMarkdown(report, idea));
  };

  // ─── FIXED: Full 7-tab export ─────────────────────────────────────────────
  const exportMarkdown = () => {
    if (!report) return;
    const blob = new Blob([buildMarkdown(report, idea)], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `kira-analysis-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareReport = () => {
    if (!report) return;
    try {
      const encoded = btoa(encodeURIComponent(JSON.stringify(report)));
      const url = `${window.location.origin}?idea=${encodeURIComponent(idea)}&data=${encoded}`;
      navigator.clipboard.writeText(url);
    } catch {}
  };

  const reset = () => {
    setPhase('input');
    setIdea('');
    setReport(null);
    setError('');
  };

  // ─── INPUT SCREEN ────────────────────────────────────────────────────────────
  if (phase === 'input') return (
    <div className="page">
      <div className="home-center">
        <h1 className="greeting">Hi, I'm Kira.</h1>
        <div className="input-wrap">
          <textarea
            ref={textareaRef}
            className="input-field"
            placeholder="What's the business idea keeping you up at night?"
            value={idea}
            onChange={(e) => setIdea(e.target.value)}
            onKeyDown={handleKey}
            rows={3}
          />
          <div className="input-bottom">
            <div className="input-left" onClick={(e) => e.stopPropagation()}>
              <div className="version-wrap">
                <button className="version-btn" onClick={() => setVersionOpen(!versionOpen)}>
                  <span className="version-label">{version}</span>
                  <span className="chevron" />
                </button>
                {versionOpen && (
                  <div className="dropdown">
                    {['Kira 1.0', 'Kira 1.1'].map((v) => (
                      <div
                        key={v}
                        className={`dd-item ${version === v ? 'active' : ''}`}
                        onClick={() => { setVersion(v); setVersionOpen(false); }}
                      >
                        {v}
                        <span className={`dd-badge ${v === 'Kira 1.1' ? 'soon' : ''}`}>
                          {v === 'Kira 1.0' ? 'current' : 'soon'}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
            <button className="send-btn" onClick={submit}>
              <span className="send-arrow" />
            </button>
          </div>
        </div>
        <div className="chips-row">
          <div className="chips">
            {chips.map((c) => (
              <button key={c} className="chip" onClick={() => setIdea(c)}>{c}</button>
            ))}
          </div>
          <button className={`shuffle-btn ${spinning ? 'spinning' : ''}`} onClick={shuffle} title="Shuffle ideas">
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="16 3 21 3 21 8" />
              <line x1="4" y1="20" x2="21" y2="3" />
              <polyline points="21 16 21 21 16 21" />
              <line x1="15" y1="15" x2="21" y2="21" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );

  // ─── RUNNING SCREEN ───────────────────────────────────────────────────────────
  if (phase === 'running') return (
    <div className="page">
      <div className="running-body">
        <div className="idea-pill">{idea}</div>
        <p className="kira-line">{kiraLine}</p>
        <div className="agents">
          {AGENTS.map((a, i) => (
            <div key={a.name} className={`agent ${agentStates[i]}`} style={{ animationDelay: `${i * 80}ms` }}>
              <span className="dot" />
              <span className="agent-name">{a.name}</span>
              {agentStates[i] === 'done' ? (
                <svg className="tick-svg animate" viewBox="0 0 15 15">
                  <circle className="tick-circle" cx="7.5" cy="7.5" r="5.8"/>
                  <polyline className="tick-check" points="4.8,7.5 6.8,9.8 10.5,5.5"/>
                </svg>
              ) : (
                <span className="agent-status">
                  {agentStates[i] === 'running' ? a.status : '—'}
                </span>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );

  // ─── ERROR SCREEN ─────────────────────────────────────────────────────────────
  if (phase === 'error') return (
    <div className="page">
      <div className="running-body">
        <div className="idea-pill">{idea}</div>
        <div className="error-card">
          <p className="error-title">Something went wrong</p>
          <p className="error-msg">{error}</p>
          <button className="reset-btn" onClick={reset}>Try again</button>
        </div>
      </div>
    </div>
  );

  // ─── RESULTS SCREEN ───────────────────────────────────────────────────────────
  const dc = report?.decisionClass || 'v-go';
  return (
    <div className="page results-page">
      <div className="results-topbar">
        <div className="results-tabs">
          {TABS.map((t) => (
            <button key={t} className={`rtab ${activeTab === t ? 'active' : ''}`} onClick={() => setActiveTab(t)}>{t}</button>
          ))}
        </div>
        <div className="results-actions">
          <button className="action-btn" onClick={exportMarkdown}>Export</button>
          <button className="action-btn" onClick={copyReport}>Copy</button>
          <button className="action-btn share" onClick={shareReport}>Share ↗</button>
        </div>
      </div>

      <div className="results-body">
        {/* VERDICT */}
        <div className={`verdict-card ${dc}`}>
          <span className="verdict-badge">{report?.decision}</span>
          <p className="verdict-reason">{report?.decisionReason}</p>
          {/* FIXED: Show pivotAngle when present */}
          {report?.pivotAngle && (
            <p className="verdict-pivot">↗ If you pivoted: {report.pivotAngle}</p>
          )}
        </div>

        {/* OVERVIEW TAB */}
        {activeTab === 'Overview' && (
          <div className="tab-content">
            <div className="metrics-grid">
              {report?.metrics?.map((m) => (
                <div key={m.l} className="metric-card">
                  <div className="metric-val">{m.v}</div>
                  <div className="metric-label">{m.l}</div>
                  {m.s && <div className="metric-sub">{m.s}</div>}
                </div>
              ))}
            </div>
            <div className="section-block">
              <div className="section-title">Market gaps</div>
              {report?.gaps?.map((g, i) => <div key={i} className="gap-row">{g}</div>)}
            </div>
            <div className="section-block">
              <div className="section-title">Risks</div>
              {report?.risks?.map((r, i) => <div key={i} className="risk-row">{typeof r === 'string' ? r : r.r}</div>)}
            </div>
            <div className="section-block">
              <div className="section-title">Revenue forecast</div>
              {report?.forecastBars?.map((b) => (
                <div key={b.label} className="forecast-row">
                  <span className="forecast-label">{b.label}</span>
                  <div className="forecast-bar-wrap">
                    <div className="forecast-bar" style={{ width: `${b.pct}%` }} />
                  </div>
                  <span className="forecast-val">{b.val}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* SCORE TAB */}
        {activeTab === 'Score' && (
          <div className="tab-content">
            <RadarChart scores={report?.scores} />
            <div className="section-block">
              {report?.scores && Object.entries(report.scores).map(([k, v]) => (
                <div key={k} className="score-row">
                  <span className="score-label">{k.replace(/([A-Z])/g, ' $1').toLowerCase()}</span>
                  <div className="score-bar-wrap"><div className="score-bar" style={{ width: `${v}%` }} /></div>
                  <span className="score-val">{v}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* MARKET TAB */}
        {activeTab === 'Market' && (
          <div className="tab-content">
            <div className="section-title">Competitor landscape</div>
            {report?.competitors?.map((c) => (
              <div key={c.name} className="competitor-card">
                <div className="comp-header">
                  <span className="comp-name">{c.name}</span>
                  <span className="comp-share">{c.share}</span>
                </div>
                <div className="comp-weakness">Weakness: {c.weakness}</div>
                <div className="comp-threat">Threat level: {c.threat}</div>
              </div>
            ))}
          </div>
        )}

        {/* PERSONAS TAB */}
        {activeTab === 'Personas' && (
          <div className="tab-content">
            {report?.personas?.map((p) => (
              <div key={p.name} className="persona-card">
                <div className="persona-header">
                  <span className="persona-name">{p.name}</span>
                  <span className="persona-tag">{p.tag}</span>
                </div>
                <div className="persona-age">Age: {p.age}</div>
                <div className="persona-row"><span className="pr-label">Channels</span><span>{p.channels}</span></div>
                <div className="persona-row"><span className="pr-label">Pain</span><span>{p.pain}</span></div>
                <div className="persona-row"><span className="pr-label">Trigger</span><span>{p.trigger}</span></div>
              </div>
            ))}
          </div>
        )}

        {/* CHANNELS TAB */}
        {activeTab === 'Channels' && (
          <div className="tab-content">
            <div className="section-title">Acquisition channels</div>
            {report?.channels?.map((c) => (
              <div key={c.name} className="channel-card">
                <div className="channel-header">
                  <span className="channel-name">{c.name}</span>
                  <span className={`fit-badge fit-${c.fit?.toLowerCase()}`}>{c.fit}</span>
                </div>
                <div className="channel-cac">CAC: {c.cac}</div>
                <div className="channel-note">{c.note}</div>
              </div>
            ))}
          </div>
        )}

        {/* LEGAL TAB */}
        {activeTab === 'Legal' && (
          <div className="tab-content">
            <div className="section-block">
              <div className="section-title">Legal requirements</div>
              {report?.legal?.map((l, i) => <div key={i} className="legal-row">{l}</div>)}
            </div>
            {report?.exit && (
              <div className="section-block">
                <div className="section-title">Exit potential</div>
                <div className="exit-grid">
                  <div className="exit-item"><div className="exit-val">{report.exit.yr3Rev}</div><div className="exit-label">Yr 3 revenue</div></div>
                  <div className="exit-item"><div className="exit-val">{report.exit.multiple}</div><div className="exit-label">Multiple</div></div>
                  <div className="exit-item"><div className="exit-val">{report.exit.yr3Val}</div><div className="exit-label">Valuation</div></div>
                </div>
                <div className="exit-buyers">Likely buyers: {report.exit.buyers}</div>
              </div>
            )}
          </div>
        )}

        {/* BLUEPRINT TAB */}
        {activeTab === 'Blueprint' && (
          <div className="tab-content">
            {report?.spec && (
              <div className="section-block">
                <div className="section-title">Product spec</div>
                {report.spec.map(([label, value], i) => (
                  <div key={i} className="spec-row">
                    <span className="spec-label">{label}</span>
                    <span className="spec-val">{value}</span>
                  </div>
                ))}
              </div>
            )}
            {report?.roadmap && (
              <div className="section-block">
                <div className="section-title">Launch roadmap</div>
                {report.roadmap.map(([time, action], i) => (
                  <div key={i} className="roadmap-row">
                    <span className="roadmap-time">{time}</span>
                    <span className="roadmap-action">{action}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        <button className="new-idea-btn" onClick={reset}>Analyze another idea</button>
      </div>
    </div>
  );
}
// tick fix
